//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimulOP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextoAjuda {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextoAjuda() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimulOP.Properties.TextoAjuda", typeof(TextoAjuda).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para os fluidos é considerando que a densidade e viscosidades se mantêm constantes independente da temperatura, já que não afetam muito os cálculos, e para o cálculo da pressão de vapor é utilizado a equação de Antoine..
        /// </summary>
        internal static string ajudaBombeamentoFluido {
            get {
                return ResourceManager.GetString("ajudaBombeamentoFluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O NPSH disponível é uma medida da diferença entre a pressão do líquido e a pressão de vapor na entrada da bomba. 
        ///
        ///Ele sempre deve ser maior que o NPSH requerido, um valor indicado pelo fabricante que representa o NPSH mínimo para garantir que não haja cavitação (formação de vapor dentro da bomba)..
        /// </summary>
        internal static string ajudaBombeamentoNPSH {
            get {
                return ResourceManager.GetString("ajudaBombeamentoNPSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apenas a tubulação de sucção afeta o valor do NPSH disponível, e que fatores como temperatura e pressão de sucção afetam muito o NPSH.
        ///
        ///Sendo desejado trabalhar com a menor perda de carga possível na tubulação de sucção, especialmente se o bombeamento é de um líquido em alta temperatura e/ou baixas pressões..
        /// </summary>
        internal static string ajudaBombeamentoSucsao {
            get {
                return ResourceManager.GetString("ajudaBombeamentoSucsao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule é uma identificação da grossura da parede dos tubos de aço carbono e inox
        ///
        ///O diâmetro em polegadas é o diâmetro nominal, diferente do diâmetro interno efetivo, e devido ao grande volume que está sendo bombeado diâmetros pequenos geram uma perda de carga muito grande.
        ///
        ///Para do fator de atrito foi utilizado a equação de Fanning..
        /// </summary>
        internal static string ajudaBombeamentoTubulacao {
            get {
                return ResourceManager.GetString("ajudaBombeamentoTubulacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para o cálculo de equilíbrio é usado a lei de Raoult para misturas ideais, usando também a equação de Antoine para estimar as pressões de vapores.
        ///
        ///Essa abordagem é válida apenas para misturas próximas da idealidade, para misturas mais complexas, ou quando há formação de azeótropos essa abordagem não pode ser utilizada..
        /// </summary>
        internal static string ajudaColunaFluido {
            get {
                return ResourceManager.GetString("ajudaColunaFluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor de alpha dá uma ideia do quão fácil é separar a mistura, quanto maior melhor, o que pode ser visto no gráfico de equilíbrio, para valores elevados de alpha a linha de equilíbrio se distancia da linha de 45º.
        ///
        ///O número de pratos apresentado considera que cada prato chega no equilíbrio, que mesmo para uma mistura ideal é uma aproximação. Para determinar o número de pratos real de uma coluna é necessário verificar a eficiência do prato, que varia conforme as características mecânicas de cada prato.
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ajudaColunaResultados {
            get {
                return ResourceManager.GetString("ajudaColunaResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condição de entrada se refere a “qualidade” da corrente que entra na coluna, e afeta mais as linhas de operações da coluna..
        /// </summary>
        internal static string ajudaCondicaoEntrada {
            get {
                return ResourceManager.GetString("ajudaCondicaoEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam porttitor laoreet libero, fermentum mollis metus cursus sit amet. Nam volutpat velit vitae odio commodo ultrices. Cras in pharetra eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer efficitur accumsan dui, vitae iaculis neque hendrerit non. Fusce aliquam blandit lorem, eget consectetur sapien. Vestibulum dapibus mollis diam sed dictum. Quisque et egestas massa. Proin congue, quam ac tristique blan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ajudaTeste {
            get {
                return ResourceManager.GetString("ajudaTeste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As escolhas dos diâmetros são os parâmetros mais importante de um trocador duplo tubo, por um lado um diâmetro menor aumenta o Reynolds do escoamento melhorando o coeficiente de troca térmica, porém aumenta muito a perda de carga..
        /// </summary>
        internal static string ajudaTrocadorDiametro {
            get {
                return ResourceManager.GetString("ajudaTrocadorDiametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Como as temperaturas de de entrada e saída dos fluidos foram definidas o parâmetro que será variado para alcançar a troca térmica será a vazão do fluido frio..
        /// </summary>
        internal static string ajudaTrocadorTubo {
            get {
                return ResourceManager.GetString("ajudaTrocadorTubo", resourceCulture);
            }
        }
    }
}
